security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # Utilisé pour recharger l'utilisateur depuis la session et autres fonctionnalités (ex: switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            # S'assurer que les outils de développement et les assets statiques sont toujours autorisés
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: /login
                default_target_path: app_dashboard
                enable_csrf: true
            logout:
                path: app_logout
                # Où rediriger après la déconnexion
                # target: app_any_route

            # Activer différentes méthodes d'authentification :
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note : Seule la *première* règle correspondante est appliquée
    # Les règles spécifiques doivent être AVANT la règle générale
    access_control:
        # Pages publiques
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        # Pages avec accès sécurisé (doivent être avant la règle générale)
        - { path: ^/objectif, roles: ROLE_USER }
        - { path: ^/seance, roles: ROLE_USER }
        - { path: ^/stats, roles: ROLE_USER }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/profil, roles: ROLE_USER }
        # Règle générale (doit être en dernier)
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # Les hachages de mots de passe sont intensifs en ressources par conception pour assurer la sécurité.
            # Dans les tests, il est sûr de réduire leur coût pour améliorer les performances.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur minimale possible pour bcrypt
                time_cost: 3 # Valeur minimale possible pour argon
                memory_cost: 10 # Valeur minimale possible pour argon
