<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container11yiqKd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container11yiqKd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container11yiqKd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container11yiqKd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container11yiqKd\App_KernelDevDebugContainer([
    'container.build_hash' => '11yiqKd',
    'container.build_id' => '96fadf85',
    'container.build_time' => 1764841250,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container11yiqKd');
