<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1q62jr5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1q62jr5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1q62jr5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1q62jr5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1q62jr5\App_KernelDevDebugContainer([
    'container.build_hash' => '1q62jr5',
    'container.build_id' => 'eca09cad',
    'container.build_time' => 1765183313,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1q62jr5');
