<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Dhzi3P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Dhzi3P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Dhzi3P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Dhzi3P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2Dhzi3P\App_KernelDevDebugContainer([
    'container.build_hash' => '2Dhzi3P',
    'container.build_id' => '61ea9796',
    'container.build_time' => 1765170442,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Dhzi3P');
